# Minimal rboot config for testing

# Map physical memory at this offset
physical_memory_offset=0xFFFF800000000000

# The path of kernel ELF
kernel_path=\EFI\zCore\example-kernel

# No initramfs needed for test
# No resolution - use default
