[package]
name = "zircon-hal-unix"
version = "0.1.0"
authors = ["Runji Wang <wangrunji0408@163.com>"]
edition = "2018"
description = "Zircon HAL implementation on Linux and macOS."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
libc = "0.2"
tempfile = "3"
lazy_static = "1.4"
zircon-object = { path = "../zircon-object" }
