#define ZX_SYS_bti_create 0
#define ZX_SYS_bti_pin 1
#define ZX_SYS_bti_release_quarantine 2
#define ZX_SYS_channel_call_etc_finish 3
#define ZX_SYS_channel_call_etc_noretry 4
#define ZX_SYS_channel_call_finish 5
#define ZX_SYS_channel_call_noretry 6
#define ZX_SYS_channel_create 7
#define ZX_SYS_channel_read 8
#define ZX_SYS_channel_read_etc 9
#define ZX_SYS_channel_write 10
#define ZX_SYS_channel_write_etc 11
#define ZX_SYS_clock_create 12
#define ZX_SYS_clock_get_boot_via_kernel 13
#define ZX_SYS_clock_get_details 14
#define ZX_SYS_clock_get_monotonic_via_kernel 15
#define ZX_SYS_clock_read 16
#define ZX_SYS_clock_update 17
#define ZX_SYS_counter_add 18
#define ZX_SYS_counter_create 19
#define ZX_SYS_counter_read 20
#define ZX_SYS_counter_write 21
#define ZX_SYS_cprng_add_entropy 22
#define ZX_SYS_cprng_draw_once 23
#define ZX_SYS_debug_read 24
#define ZX_SYS_debug_send_command 25
#define ZX_SYS_debug_write 26
#define ZX_SYS_debuglog_create 27
#define ZX_SYS_debuglog_read 28
#define ZX_SYS_debuglog_write 29
#define ZX_SYS_event_create 30
#define ZX_SYS_eventpair_create 31
#define ZX_SYS_exception_get_process 32
#define ZX_SYS_exception_get_thread 33
#define ZX_SYS_fifo_create 34
#define ZX_SYS_fifo_read 35
#define ZX_SYS_fifo_write 36
#define ZX_SYS_futex_get_owner 37
#define ZX_SYS_futex_requeue 38
#define ZX_SYS_futex_requeue_single_owner 39
#define ZX_SYS_futex_wait 40
#define ZX_SYS_futex_wake 41
#define ZX_SYS_futex_wake_single_owner 42
#define ZX_SYS_guest_create 43
#define ZX_SYS_guest_set_trap 44
#define ZX_SYS_handle_close 45
#define ZX_SYS_handle_close_many 46
#define ZX_SYS_handle_duplicate 47
#define ZX_SYS_handle_replace 48
#define ZX_SYS_interrupt_ack 49
#define ZX_SYS_interrupt_bind 50
#define ZX_SYS_interrupt_create 51
#define ZX_SYS_interrupt_destroy 52
#define ZX_SYS_interrupt_trigger 53
#define ZX_SYS_interrupt_wait 54
#define ZX_SYS_iob_allocate_id 55
#define ZX_SYS_iob_create 56
#define ZX_SYS_iob_create_shared_region 57
#define ZX_SYS_iob_writev 58
#define ZX_SYS_iommu_create 59
#define ZX_SYS_ioports_release 60
#define ZX_SYS_ioports_request 61
#define ZX_SYS_job_create 62
#define ZX_SYS_job_set_critical 63
#define ZX_SYS_job_set_policy 64
#define ZX_SYS_ktrace_control 65
#define ZX_SYS_ktrace_read 66
#define ZX_SYS_membarrier_sync_process_data 67
#define ZX_SYS_membarrier_sync_process_insn 68
#define ZX_SYS_msi_allocate 69
#define ZX_SYS_msi_create 70
#define ZX_SYS_nanosleep 71
#define ZX_SYS_object_get_child 72
#define ZX_SYS_object_get_info 73
#define ZX_SYS_object_get_property 74
#define ZX_SYS_object_set_profile 75
#define ZX_SYS_object_set_property 76
#define ZX_SYS_object_signal 77
#define ZX_SYS_object_signal_peer 78
#define ZX_SYS_object_wait_async 79
#define ZX_SYS_object_wait_many 80
#define ZX_SYS_object_wait_one 81
#define ZX_SYS_pager_create 82
#define ZX_SYS_pager_create_vmo 83
#define ZX_SYS_pager_detach_vmo 84
#define ZX_SYS_pager_op_range 85
#define ZX_SYS_pager_query_dirty_ranges 86
#define ZX_SYS_pager_query_vmo_stats 87
#define ZX_SYS_pager_supply_pages 88
#define ZX_SYS_pmt_unpin 89
#define ZX_SYS_port_cancel 90
#define ZX_SYS_port_cancel_key 91
#define ZX_SYS_port_create 92
#define ZX_SYS_port_queue 93
#define ZX_SYS_port_wait 94
#define ZX_SYS_process_create 95
#define ZX_SYS_process_create_shared 96
#define ZX_SYS_process_exit 97
#define ZX_SYS_process_read_memory 98
#define ZX_SYS_process_start 99
#define ZX_SYS_process_write_memory 100
#define ZX_SYS_profile_create 101
#define ZX_SYS_resource_create 102
#define ZX_SYS_restricted_bind_state 103
#define ZX_SYS_restricted_enter 104
#define ZX_SYS_restricted_kick 105
#define ZX_SYS_restricted_unbind_state 106
#define ZX_SYS_sampler_create 107
#define ZX_SYS_sampler_read 108
#define ZX_SYS_sampler_start 109
#define ZX_SYS_sampler_stop 110
#define ZX_SYS_smc_call 111
#define ZX_SYS_socket_create 112
#define ZX_SYS_socket_read 113
#define ZX_SYS_socket_set_disposition 114
#define ZX_SYS_socket_write 115
#define ZX_SYS_stream_create 116
#define ZX_SYS_stream_readv 117
#define ZX_SYS_stream_readv_at 118
#define ZX_SYS_stream_seek 119
#define ZX_SYS_stream_writev 120
#define ZX_SYS_stream_writev_at 121
#define ZX_SYS_syscall_next_1 122
#define ZX_SYS_syscall_test_handle_create 123
#define ZX_SYS_syscall_test_rust_handle 124
#define ZX_SYS_syscall_test_rust_inoutptr 125
#define ZX_SYS_syscall_test_rust_inptr 126
#define ZX_SYS_syscall_test_rust_outptr 127
#define ZX_SYS_syscall_test_rust_wrapper 128
#define ZX_SYS_syscall_test_rust_0 129
#define ZX_SYS_syscall_test_rust_1 130
#define ZX_SYS_syscall_test_rust_2 131
#define ZX_SYS_syscall_test_rust_3 132
#define ZX_SYS_syscall_test_rust_4 133
#define ZX_SYS_syscall_test_rust_5 134
#define ZX_SYS_syscall_test_rust_6 135
#define ZX_SYS_syscall_test_rust_7 136
#define ZX_SYS_syscall_test_rust_8 137
#define ZX_SYS_syscall_test_widening_signed_narrow 138
#define ZX_SYS_syscall_test_widening_signed_wide 139
#define ZX_SYS_syscall_test_widening_unsigned_narrow 140
#define ZX_SYS_syscall_test_widening_unsigned_wide 141
#define ZX_SYS_syscall_test_wrapper 142
#define ZX_SYS_syscall_test_0 143
#define ZX_SYS_syscall_test_1 144
#define ZX_SYS_syscall_test_2 145
#define ZX_SYS_syscall_test_3 146
#define ZX_SYS_syscall_test_4 147
#define ZX_SYS_syscall_test_5 148
#define ZX_SYS_syscall_test_6 149
#define ZX_SYS_syscall_test_7 150
#define ZX_SYS_syscall_test_8 151
#define ZX_SYS_system_get_event 152
#define ZX_SYS_system_get_performance_info 153
#define ZX_SYS_system_mexec 154
#define ZX_SYS_system_mexec_payload_get 155
#define ZX_SYS_system_powerctl 156
#define ZX_SYS_system_set_performance_info 157
#define ZX_SYS_system_suspend_enter 158
#define ZX_SYS_system_watch_memory_stall 159
#define ZX_SYS_task_create_exception_channel 160
#define ZX_SYS_task_kill 161
#define ZX_SYS_task_suspend 162
#define ZX_SYS_task_suspend_token 163
#define ZX_SYS_thread_create 164
#define ZX_SYS_thread_exit 165
#define ZX_SYS_thread_legacy_yield 166
#define ZX_SYS_thread_raise_exception 167
#define ZX_SYS_thread_read_state 168
#define ZX_SYS_thread_set_rseq 169
#define ZX_SYS_thread_start_regs 170
#define ZX_SYS_thread_write_state 171
#define ZX_SYS_ticks_get_boot_via_kernel 172
#define ZX_SYS_ticks_get_via_kernel 173
#define ZX_SYS_timer_cancel 174
#define ZX_SYS_timer_create 175
#define ZX_SYS_timer_set 176
#define ZX_SYS_vcpu_create 177
#define ZX_SYS_vcpu_enter 178
#define ZX_SYS_vcpu_interrupt 179
#define ZX_SYS_vcpu_kick 180
#define ZX_SYS_vcpu_read_state 181
#define ZX_SYS_vcpu_write_state 182
#define ZX_SYS_vmar_allocate 183
#define ZX_SYS_vmar_destroy 184
#define ZX_SYS_vmar_map 185
#define ZX_SYS_vmar_map_clock 186
#define ZX_SYS_vmar_map_iob 187
#define ZX_SYS_vmar_op_range 188
#define ZX_SYS_vmar_protect 189
#define ZX_SYS_vmar_unmap 190
#define ZX_SYS_vmo_create 191
#define ZX_SYS_vmo_create_child 192
#define ZX_SYS_vmo_create_contiguous 193
#define ZX_SYS_vmo_create_physical 194
#define ZX_SYS_vmo_get_size 195
#define ZX_SYS_vmo_get_stream_size 196
#define ZX_SYS_vmo_op_range 197
#define ZX_SYS_vmo_read 198
#define ZX_SYS_vmo_replace_as_executable 199
#define ZX_SYS_vmo_set_cache_policy 200
#define ZX_SYS_vmo_set_size 201
#define ZX_SYS_vmo_set_stream_size 202
#define ZX_SYS_vmo_transfer_data 203
#define ZX_SYS_vmo_write 204

// Legacy syscalls retained so their implementations remain buildable. These
// numbers are outside the current Zircon syscall table and cannot be issued by
// current userspace.
#define ZX_SYS_thread_start 1000
#define ZX_SYS_socket_shutdown 1001
#define ZX_SYS_clock_get 1002
#define ZX_SYS_clock_adjust 1003
#define ZX_SYS_vmar_unmap_handle_close_thread_exit 1004
#define ZX_SYS_futex_wake_handle_close_thread_exit 1005
#define ZX_SYS_pc_firmware_tables 1006
#define ZX_SYS_pci_add_subtract_io_range 1007
#define ZX_SYS_pci_cfg_pio_rw 1008
#define ZX_SYS_pci_init 1009
#define ZX_SYS_pci_get_nth_device 1010
#define ZX_SYS_pci_map_interrupt 1011
#define ZX_SYS_pci_get_bar 1012
#define ZX_SYS_pci_enable_bus_master 1013
#define ZX_SYS_pci_query_irq_mode 1014
#define ZX_SYS_pci_set_irq_mode 1015
#define ZX_SYS_pci_config_read 1016
#define ZX_SYS_pci_config_write 1017
