[workspace]
members = [
    "drivers",
    "kernel-hal",
    "zircon-object",
    "zircon-syscall",
    "linux-object",
    "linux-syscall",
    "loader",
    "zCore",
    "z-config",
    "xtask",
]
default-members = ["xtask"]
exclude = ["zircon-user", "rboot"]
resolver = "2"

[patch."https://github.com/DeathWish5/PreemptiveScheduler"]
executor = { path = "third-party/executor" }

[patch."https://github.com/rzswh/region-allocator"]
region-alloc = { path = "third-party/region-alloc" }

[profile.release]
lto = true
debug = true
