[workspace]
resolver = "1"
members = [
    "drivers",
    "kernel-hal",
    "zircon-object",
    "zircon-syscall",
    "linux-object",
    "linux-syscall",
    "loader",
    "zCore",
    "z-config",
    "xtask",
]
default-members = ["xtask"]
exclude = [
    "zircon-user",
    "rboot",
    "vendor/preemptive-scheduler",
    "vendor/region-allocator",
]

[patch."https://github.com/DeathWish5/PreemptiveScheduler"]
executor = { path = "vendor/preemptive-scheduler" }

[profile.release]
lto = true
debug = true
