[workspace]
members = [
    "drivers",
    "kernel-hal",
    "zircon-object",
    "zircon-syscall",
    "linux-object",
    "linux-syscall",
    "loader",
    "zCore",
    "z-config",
    "xtask",
    "third-party/executor",
    "third-party/region-alloc",
]
default-members = ["xtask"]
exclude = ["zircon-user", "rboot"]
resolver = "2"

[profile.release]
lto = true
debug = true
