var N = null;var sourcesIndex = {};
sourcesIndex["kernel_hal"] = {"name":"","dirs":[{"name":"common","files":["addr.rs","console.rs","context.rs","defs.rs","future.rs","mem.rs","mod.rs","thread.rs","user.rs","vdso.rs","vm.rs"]},{"name":"libos","files":["boot.rs","config.rs","cpu.rs","drivers.rs","dummy.rs","mem.rs","mock_mem.rs","mod.rs","net.rs","special.rs","thread.rs","timer.rs","vdso.rs","vm.rs"]},{"name":"utils","files":["init_once.rs","mod.rs"]}],"files":["config.rs","drivers.rs","hal_fn.rs","kernel_handler.rs","lib.rs","macros.rs"]};
sourcesIndex["linux_object"] = {"name":"","dirs":[{"name":"fs","dirs":[{"name":"devfs","dirs":[{"name":"input","files":["event.rs","mice.rs","mod.rs"]}],"files":["fbdev.rs","mod.rs","random.rs"]}],"files":["file.rs","ioctl.rs","mod.rs","pipe.rs","pseudo.rs","rcore_fs_wrapper.rs","stdio.rs"]},{"name":"ipc","files":["mod.rs","semary.rs","shared_mem.rs"]},{"name":"loader","files":["abi.rs","mod.rs"]},{"name":"net","files":["mod.rs","socket_address.rs","tcp.rs","udp.rs"]},{"name":"signal","files":["action.rs","mod.rs"]},{"name":"sync","files":["event_bus.rs","mod.rs","semaphore.rs"]}],"files":["error.rs","lib.rs","process.rs","thread.rs","time.rs"]};
sourcesIndex["linux_syscall"] = {"name":"","dirs":[{"name":"file","files":["dir.rs","fd.rs","file.rs","mod.rs","poll.rs","stat.rs"]}],"files":["ipc.rs","lib.rs","misc.rs","net.rs","signal.rs","task.rs","time.rs","vm.rs"]};
sourcesIndex["zcore_drivers"] = {"name":"","dirs":[{"name":"builder","files":["devicetree.rs","mod.rs"]},{"name":"display","files":["mod.rs","uefi.rs"]},{"name":"input","files":["input_event_codes.rs","mod.rs","mouse.rs"]},{"name":"io","files":["mmio.rs","mod.rs","pio.rs"]},{"name":"irq","dirs":[{"name":"x86_apic","files":["consts.rs","ioapic.rs","lapic.rs","mod.rs"]}],"files":["mod.rs"]},{"name":"mock","dirs":[{"name":"graphic","files":["mod.rs","sdl.rs"]}],"files":["display.rs","input.rs","mod.rs","uart.rs"]},{"name":"net","files":["loopback.rs","mod.rs"]},{"name":"scheme","files":["block.rs","display.rs","event.rs","input.rs","irq.rs","mod.rs","net.rs","uart.rs"]},{"name":"uart","files":["buffered.rs","mod.rs","uart_16550.rs"]},{"name":"utils","files":["devicetree.rs","event_listener.rs","graphic_console.rs","id_allocator.rs","irq_manager.rs","mod.rs"]},{"name":"virtio","files":["blk.rs","console.rs","gpu.rs","input.rs","mod.rs"]}],"files":["lib.rs","prelude.rs"]};
sourcesIndex["zcore_loader"] = {"name":"","files":["lib.rs","linux.rs","zircon.rs"]};
sourcesIndex["zircon_object"] = {"name":"","dirs":[{"name":"dev","dirs":[{"name":"interrupt","files":["event_interrupt.rs","mod.rs","pci_interrupt.rs","virtual_interrupt.rs"]},{"name":"pci","files":["bus.rs","caps.rs","config.rs","mod.rs","nodes.rs","pci_init_args.rs","pio.rs"]}],"files":["bti.rs","iommu.rs","mod.rs","pmt.rs","resource.rs"]},{"name":"ipc","files":["channel.rs","fifo.rs","mod.rs","socket.rs"]},{"name":"object","files":["handle.rs","mod.rs","rights.rs","signal.rs"]},{"name":"signal","files":["event.rs","eventpair.rs","futex.rs","mod.rs","port.rs","port_packet.rs","timer.rs"]},{"name":"task","dirs":[{"name":"thread","files":["thread_state.rs"]}],"files":["exception.rs","job.rs","job_policy.rs","mod.rs","process.rs","suspend_token.rs","thread.rs"]},{"name":"util","files":["block_range.rs","elf_loader.rs","kcounter.rs","mod.rs"]},{"name":"vm","dirs":[{"name":"vmo","files":["mod.rs","paged.rs","physical.rs","slice.rs"]}],"files":["mod.rs","stream.rs","vmar.rs"]}],"files":["debuglog.rs","error.rs","lib.rs"]};
sourcesIndex["zircon_syscall"] = {"name":"","files":["channel.rs","consts.rs","cprng.rs","ddk.rs","debug.rs","debuglog.rs","exception.rs","fifo.rs","futex.rs","handle.rs","lib.rs","object.rs","pci.rs","port.rs","resource.rs","signal.rs","socket.rs","stream.rs","system.rs","task.rs","time.rs","vmar.rs","vmo.rs"]};
createSourceSidebar();
