(function() {var implementors = {};
implementors["kernel_hal_unix"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"kernel_hal_unix/struct.PhysFrame.html\" title=\"struct kernel_hal_unix::PhysFrame\">PhysFrame</a>","synthetic":false,"types":["kernel_hal_unix::PhysFrame"]}];
implementors["zircon_object"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"zircon_object/hal/struct.PhysFrame.html\" title=\"struct zircon_object::hal::PhysFrame\">PhysFrame</a>","synthetic":false,"types":["zircon_object::hal::PhysFrame"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"zircon_object/io/struct.EventPair.html\" title=\"struct zircon_object::io::EventPair\">EventPair</a>","synthetic":false,"types":["zircon_object::io::event::EventPair"]},{"text":"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"zircon_object/ipc/struct.Channel_.html\" title=\"struct zircon_object::ipc::Channel_\">Channel_</a>&lt;T&gt;","synthetic":false,"types":["zircon_object::ipc::channel::Channel_"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"zircon_object/vm/struct.VmMapping.html\" title=\"struct zircon_object::vm::VmMapping\">VmMapping</a>","synthetic":false,"types":["zircon_object::vm::vmar::VmMapping"]}];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()