use std::io::Write;

fn main() {
    println!("cargo:rerun-if-changed=src/zx-syscall-numbers.h");

    let mut fout = std::fs::File::create("src/consts.rs").unwrap();
    writeln!(fout, "// Generated by build.rs. DO NOT EDIT.").unwrap();
    writeln!(fout, "#![allow(dead_code)]\n").unwrap();

    let data = std::fs::read_to_string("src/zx-syscall-numbers.h").unwrap();
    for line in data.split('\n') {
        if !line.starts_with("#define") {
            continue;
        }
        let mut iter = line.split(' ');
        let _ = iter.next().unwrap();
        let name = iter.next().unwrap();
        let id = iter.next().unwrap();

        let name = &name[3..].to_uppercase();
        writeln!(fout, "pub const {}: u32 = {};", name, id).unwrap();
    }
}
