apk-policy(8)

# NAME

apk policy - show repository policy for packages

# SYNOPSIS

*apk policy* [<_options_>...] _packages_...

# DESCRIPTION

*apk policy* shows apk's repository policy for the specified packages. It
prints matching packages and their versions available from configured
repositories (see *apk-repositories*(5)), sorted by ascending version.

# OPTIONS

The global options (see *apk*(8)) and query options (see *apk-query*(8))
are supported.
